# Generated by Django 5.0.3 on 2024-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='doc_titles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='doc_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
