# Generated by Django 5.0.3 on 2024-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rag_score',
            field=models.FloatField(default=-1.0),
        ),
    ]
