services:
  qdrant:
    image: ghcr.io/dakoro/projet_simplon/qdrant
    container_name: qdrant_store
    build: 
      context: ..
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
  mlflow:
    image: ghcr.io/dakoro/projet_simplon/mflow
    build:
      context: ..
      dockerfile: mlflow/Dockerfile
    ports:
     - "8083:8083"
    expose:
      - 8083