# syntax=docker/dockerfile:1

FROM python:3.10

WORKDIR /


COPY ../api/model ./api/model
COPY ../models ./models
COPY ../files/pkl ./files/pkl
COPY ../.env .
COPY ../Makefile .

RUN pip install --no-cache-dir --upgrade -r ../api/model/requirements.txt

EXPOSE 8082

CMD ["make", "api_model_container"]
