FROM python:3.10-slim-buster

WORKDIR /

COPY ./mlflow ./mlflow
COPY ./Makefile .

RUN apt-get update
RUN apt-get install make
RUN pip install --upgrade pip
RUN pip install --no-cache-dir mlflow

CMD ["make", "mlflow-server"]