services:
  api:
    build:
      context: ..
      dockerfile: api/model/Dockerfile
    container_name: api_model
    ports: 
      - "8082:8082"
    expose:
      - 8082
    depends_on:
      - qdrant
      - mlflow
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_store
    build: 
      context: ..
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
    volumes:
      - ../qdrant_storage:/qdrant/storage
  mlflow:
    build:
      context: ..
      dockerfile: ./mlflow/Dockerfile
    container_name: mlflow-server
    ports:
     - "8083:8083"
    expose:
      - 8083
    volumes:
      - ../mlflow:/mlflow