services:
  mlflow:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.mlflow
    container_name: mlflow-server
    ports:
     - "8083:8083"
    expose:
      - 8083
    volumes:
      - ../mlflow:/mlflow
  
  api-model:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api_model
    container_name: api-model
    ports:
      - "8082:8082"
    expose:
      - 8082