services:
  mlflow:
    build:
      context: ..
      dockerfile: ./mlflow/Dockerfile
    container_name: mlflow-server
    ports:
     - "8083:8083"
    expose:
      - 8083
    volumes:
      - ../mlflow:/mlflow