name: Test Api Model

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests for the Model Api
    runs-on: ubuntu-latest
    services:
      mlflow:
        image: ghcr.io/dakoro/projet_simplon/mflow:latest
        ports:
        - 8083:8083

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r api/model/requirements.txt
        pip install --no-cache-dir pytest

    - name: Run tests
      env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        QDRANT_URI: ${{ secrets.QDRANT_URI }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      run: |
        make test-api-model