name: Test Application

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests for Arxiv Application
    runs-on: ubuntu-latest
    services:
      mlflow:
        image: ghcr.io/dakoro/projet_simplon/mlflow:latest
        ports:
        - 8083:8083
      api_model:
        image: ghcr.io/dakoro/projet_simplon/api_model:latest
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          QDRANT_URI: ${{ secrets.QDRANT_URI }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        ports:
        - 8080:8082

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        pip cache purge
        python -m pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir -r arxiv_app/requirements.txt
        pip install --no-cache-dir pytest-django
        python scripts/nltk_download.py


    - name: Run tests
      env:
        API_MODEL_URL: "http://localhost:8082"
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      run: |
        make test-app
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./docker/Dockerfile.app
        push: true
        tags: ghcr.io/dakoro/projet_simplon/app:latest