name: Test Api Data

on: [push]

jobs:
  test:
    name: Run Tests for the Model Api
    runs-on: ubuntu-latest
    environment: test_env

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/model/requirements.txt
        pip install pytest
      
    - name: build test-container
      run: make test-api-container

    - name: Run tests
      env:
        JWT_SECRET_KEY: ${{ vars.JWT_SECRET_KEY }}
        JWT_REFRESH_SECRET_KEY: ${{ vars.JWT_REFRESH_SECRET_KEY }}
        OPENAI_KEY: ${{ vars.OPENAI_KEY }}
        MLFLOW_URI: ${{ vars.MLFLOW_URI }}
        QDRANT_URI: ${{ vars.QDRANT_URI }}
        KMEANS_RUN_URI: ${{ vars.KMEANS_RUN_URI }}
      run: |
        cd api/model && pytest -vv