name: Test Application

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests for Arxiv Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        pip cache purge
        python -m pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir -r arxiv_app/requirements.txt
        pip install --no-cache-dir pytest-django

    - name: Run tests
      run: |
        make test-app
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./docker/Dockerfile.app
        push: true
        tags: ghcr.io/dakoro/projet_simplon/app:latest