name: Test Training pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests for experiments scripts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir -r tests/requirements-test.txt
        pip install --no-cache-dir pytest

    - name: Run tests
      run: |
        pytest -vv tests