channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.1
- pip:
  - mlflow==2.15.1
  - attrs==23.2.0
  - click==8.1.7
  - cython==0.29.37
  - h2==4.1.0
  - openai==1.30.4
  - rich==13.7.1
  - tenacity==8.2.3
  - tiktoken==0.7.0
name: mlflow-env
